# Generated by Django 2.2.1 on 2019-12-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类名称', 'verbose_name_plural': '分类名称'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
