# Generated by Django 2.2.1 on 2019-12-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
